<a href="https://colab.research.google.com/github/sppu33/DSBDAL/blob/main/dsbdal3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Descriptive Statistics - Measures of Central Tendency and variability

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("nba.csv")

In [5]:
df.head()

            Name            Team  Number Position  ...  Height Weight            College     Salary
0  Avery Bradley  Boston Celtics     0.0       PG  ...     6-2  180.0              Texas  7730337.0
1    Jae Crowder  Boston Celtics    99.0       SF  ...     6-6  235.0          Marquette  6796117.0
2   John Holland  Boston Celtics    30.0       SG  ...     6-5  205.0  Boston University        NaN
3    R.J. Hunter  Boston Celtics    28.0       SG  ...     6-5  185.0      Georgia State  1148640.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  ...    6-10  231.0                NaN  5000000.0

[5 rows x 9 columns]

In [6]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [7]:
df.shape

(458, 9)

# filling null places with measures of central tendency

In [9]:
mode= df['College'].mode()[0]
df['College'].fillna(mode,inplace=True)
mode

<ipython-input-9-27cf79bafa93>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['College'].fillna(mode,inplace=True)

'Kentucky'

In [10]:
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

<ipython-input-10-8332c1905e34>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)

In [11]:
df['College'].value_counts()

College
Kentucky            107
Duke                 20
Kansas               18
North Carolina       16
UCLA                 15
                   ...
Morehead State        1
Weber State           1
Central Michigan      1
Westchester CC        1
Lehigh                1
Name: count, Length: 118, dtype: int64

In [12]:
collegeGroups=df.groupby(df['College'])

In [13]:
collegeGroups.describe()

                 Number                              ...     Salary
                  count       mean        std   min  ...        25%        50%         75%         max
College                                              ...
Alabama             3.0  22.333333  26.764404   0.0  ...  1082529.5  1320000.0   1710000.0   2100000.0
Arizona            13.0  18.076923  12.365689   0.0  ...   947276.0  2841960.0   4000000.0  11710456.0
Arizona State       2.0  16.000000   4.242641  13.0  ...  4022692.5  7933941.0  11845189.5  15756438.0
Arkansas            3.0   3.000000   1.732051   2.0  ...   826527.0  1391160.0   3938823.0   6486486.0
Baylor              1.0  13.000000        NaN  13.0  ...   981348.0   981348.0    981348.0    981348.0
...                 ...        ...        ...   ...  ...        ...        ...         ...         ...
Western Michigan    1.0  42.000000        NaN  42.0  ...   845059.0   845059.0    845059.0    845059.0
Wichita State       1.0  11.000000        NaN  11.0  ...   845059.0   845059.0    845059.0    845059.0
Wisconsin           5.0  28.200000  13.608821   7.0  ...  1035000.0  1646400.0   2612520.0   4053446.0
Wyoming             1.0   7.000000        NaN   7.0  ...  1155600.0  1155600.0   1155600.0   1155600.0
Xavier              1.0  30.000000        NaN  30.0  ...  1499187.0  1499187.0   1499187.0   1499187.0

[118 rows x 32 columns]

In [14]:
meanSalaryByCollege=collegeGroups['Salary'].mean()

In [15]:
meanSalaryByCollege

College
Alabama             1.421686e+06
Arizona             3.325948e+06
Arizona State       7.933941e+06
Arkansas            2.713180e+06
Baylor              9.813480e+05
                        ...
Western Michigan    8.450590e+05
Wichita State       8.450590e+05
Wisconsin           1.974492e+06
Wyoming             1.155600e+06
Xavier              1.499187e+06
Name: Salary, Length: 118, dtype: float64

converting Salary Values to List

In [16]:
incomeListByCollege=collegeGroups['Salary'].apply(list)
incomeListByCollege

College
Alabama                              [2100000.0, 845059.0, 1320000.0]
Arizona             [1335480.0, 4000000.0, 525093.0, 11710456.0, 2...
Arizona State                                  [111444.0, 15756438.0]
Arkansas                             [1391160.0, 6486486.0, 261894.0]
Baylor                                                     [981348.0]
                                          ...
Western Michigan                                           [845059.0]
Wichita State                                              [845059.0]
Wisconsin           [1035000.0, 525093.0, 4053446.0, 1646400.0, 26...
Wyoming                                                   [1155600.0]
Xavier                                                    [1499187.0]
Name: Salary, Length: 118, dtype: object

# to categorize (or bin) the "Age" column into age groups.

In [17]:
bins=[20,25,30,35,40]
labels=['20-24','25-29','30-34','35-49']
ageGroups=pd.cut(df['Age'],bins=bins, labels=labels, right=False)

In [21]:
ageGroups.value_counts()

Age
25-29    181
20-24    152
30-34     90
35-49     29
Name: count, dtype: int64

In [22]:
df.head()

            Name            Team  Number Position  ...  Height Weight            College        Salary
0  Avery Bradley  Boston Celtics     0.0       PG  ...     6-2  180.0              Texas  7.730337e+06
1    Jae Crowder  Boston Celtics    99.0       SF  ...     6-6  235.0          Marquette  6.796117e+06
2   John Holland  Boston Celtics    30.0       SG  ...     6-5  205.0  Boston University  4.842684e+06
3    R.J. Hunter  Boston Celtics    28.0       SG  ...     6-5  185.0      Georgia State  1.148640e+06
4  Jonas Jerebko  Boston Celtics     8.0       PF  ...    6-10  231.0           Kentucky  5.000000e+06

[5 rows x 9 columns]

In [23]:
df['Age Group']=ageGroups

In [24]:
df.head()

            Name            Team  Number  ...            College        Salary Age Group
0  Avery Bradley  Boston Celtics     0.0  ...              Texas  7.730337e+06     25-29
1    Jae Crowder  Boston Celtics    99.0  ...          Marquette  6.796117e+06     25-29
2   John Holland  Boston Celtics    30.0  ...  Boston University  4.842684e+06     25-29
3    R.J. Hunter  Boston Celtics    28.0  ...      Georgia State  1.148640e+06     20-24
4  Jonas Jerebko  Boston Celtics     8.0  ...           Kentucky  5.000000e+06     25-29

[5 rows x 10 columns]

In [25]:
SalaryListByAgeGroup=df.groupby('Age Group')['Salary'].apply(list)
SalaryListByAgeGroup

<ipython-input-25-c5f13479050a>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  SalaryListByAgeGroup=df.groupby('Age Group')['Salary'].apply(list)

Age Group
20-24    [1148640.0, 1170960.0, 1824360.0, 3431040.0, 2...
25-29    [7730337.0, 6796117.0, 4842684.105381166, 5000...
30-34    [6300000.0, 8000000.0, 1635476.0, 22875000.0, ...
35-49    [4842684.105381166, 2900000.0, 5675000.0, 3376...
Name: Salary, dtype: object

# # Assignment Part 2

In [26]:
df2=pd.read_csv('Iris.csv')

In [27]:
df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [28]:
df2.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [30]:
df2['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [31]:
setosa_data=df2[df2['Species']=='Iris-setosa']
versicolor_data=df2[df2['Species']=='Iris-versicolor']
virginica_data=df2[df2['Species']=='Iris-virginica']

In [37]:
setosa_data.describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [36]:
versicolor_data.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [35]:
virginica_data.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000